name: Vala Code
desc: Vala support for Visual Studio Code
permalink: /:name/
excerpt_separator: ""
exclude:
  - pubspec.yaml
  - tool/
collections:
  docs:
    output: true
    permalink: /docs/:name/
  releases:
    output: true
    permalink: /releases/:name/
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: doc
  - scope:
      path: _releases
      type: releases
    values:
      layout: release
